// <auto-generated />
using System;
using ABPD08.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ABPD08.Migrations
{
    [DbContext(typeof(CodeFirstContext))]
    [Migration("20210505194813_AddedPatientMedicamentDoctor")]
    partial class AddedPatientMedicamentDoctor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APBD11.Models.Doctor", b =>
            {
                b.Property<int>("IdDoctor")
                    .HasColumnType("int");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)")
                    .HasMaxLength(100);

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)")
                    .HasMaxLength(100);

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)")
                    .HasMaxLength(100);

                b.HasKey("IdDoctor")
                    .HasName("Doctor_PK");

                b.ToTable("Doctor");

                b.HasData(
                    new
                    {
                        IdDoctor = 1,
                        Email = "johngabbana@gmail.com",
                        FirstName = "John",
                        LastName = "Gabbana"
                    },
                    new
                    {
                        IdDoctor = 2,
                        Email = "karolNowak@gmail.com",
                        FirstName = "Karol",
                        LastName = "Nowak"
                    },
                    new
                    {
                        IdDoctor = 3,
                        Email = "janKowalski@gmail.com",
                        FirstName = "Jan",
                        LastName = "Kowalski"
                    });
            });

            modelBuilder.Entity("APBD11.Models.Medicament", b =>
            {
                b.Property<int>("IdMedicament")
                    .HasColumnType("int");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)")
                    .HasMaxLength(100);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)")
                    .HasMaxLength(100);

                b.Property<string>("Type")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)")
                    .HasMaxLength(100);

                b.HasKey("IdMedicament")
                    .HasName("Medicament_PK");

                b.ToTable("Medicament");

                b.HasData(
                    new
                    {
                        IdMedicament = 1,
                        Description = "opis propranololu",
                        Name = "Propranolol",
                        Type = "Healthy"
                    },
                    new
                    {
                        IdMedicament = 2,
                        Description = "opis Ibuprom",
                        Name = "Ibuprom",
                        Type = "Przeciwbolowy"
                    },
                    new
                    {
                        IdMedicament = 3,
                        Description = "opis Apapu",
                        Name = "Apap",
                        Type = "Przeciwbolowy"
                    },
                    new
                    {
                        IdMedicament = 4,
                        Description = "opis Apapu",
                        Name = "Apap",
                        Type = "Przeciwbolowy"
                    },
                    new
                    {
                        IdMedicament = 5,
                        Description = "opis Adderallu",
                        Name = "Adderall",
                        Type = "Szybki"
                    });
            });

            modelBuilder.Entity("APBD11.Models.Patient", b =>
            {
                b.Property<int>("IdPatient")
                    .HasColumnType("int");

                b.Property<DateTime>("Birthdate")
                    .HasColumnType("datetime2");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)")
                    .HasMaxLength(100);

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)")
                    .HasMaxLength(100);

                b.HasKey("IdPatient")
                    .HasName("Patient_PK");

                b.ToTable("Patient");

                b.HasData(
                    new
                    {
                        IdPatient = 1,
                        Birthdate = new DateTime(1990, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        FirstName = "Basia",
                        LastName = "Ross"
                    },
                    new
                    {
                        IdPatient = 2,
                        Birthdate = new DateTime(1970, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        FirstName = "Kevin",
                        LastName = "Kostner"
                    },
                    new
                    {
                        IdPatient = 3,
                        Birthdate = new DateTime(1982, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        FirstName = "Tim",
                        LastName = "Cook"
                    });
            });
#pragma warning restore 612, 618
        }
    }
}
